name: Java CI with Maven

on:
    push:
    pull_request:
        branches: [ "main" ]

jobs:
    build:

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: ironhide
                    POSTGRES_PASSWORD: CSzuvcUEoc
                    POSTGRES_DB: audit_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'corretto'
            -   name: Build with Maven
                run: |
                    pwd
                    java -version
                    ./mvnw --version
                    ./mvnw -B package --file pom.xml -P local
            -   name: Upload JAR
                uses: actions/upload-artifact@v4
                continue-on-error: true
                with:
                    name: IronHideBUILD
                    path: /home/runner/work/ironhide/ironhide/target/*.jar
